### ISSUE TITLE
Bug: the `--welcome false` CLI option doesn't fully remove the welcome page

### ISSUE THREAD

**Issue by jenweber** [ember-cli/ember-octane-blueprint#100]
If you run `ember new ember-quickstart -b @ember/octane-app-blueprint --welcome false`, the welcome addon is excluded from package.json, but it is not removed from `application.hbs`.

Using the `welcome` option in a regular Ember version (3.9) works as expected.

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-octane-blueprint/pull/102
