### ISSUE TITLE
`.eslintignore` missing from addon blueprint

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-octane-blueprint#104]
[`octane-addon-blueprint/files`](https://github.com/ember-cli/ember-octane-blueprint/tree/master/packages/%40ember/octane-addon-blueprint/files) vs [`octane-app-blueprint/files`](https://github.com/ember-cli/ember-octane-blueprint/tree/master/packages/%40ember/octane-app-blueprint/files).

This leads to a _seemingly_ hanging eslint when run on a project that has `dist`, `node_modules`, etc.

**Comment by Panman8201** [comment]
FYI, working on this in #105

**Comment by NullVoxPopuli** [comment]
Confirmed working on windows:
![image](https://user-images.githubusercontent.com/199018/59962931-0e85fa00-94ba-11e9-8076-0b6b9e00f597.png)
