### ISSUE TITLE
ember new blueprint fails with Unexpected token function

### ISSUE THREAD

**Issue by manurampandit** [ember-cli/ember-octane-blueprint#120]
**Below is the error message:** 
Error creating new application. Removing generated directory `./ember-quickstart`
Unexpected token function

**Stack Trace and Error Report:** /var/folders/32/t6t2nn2x63s9k3dhh_3dmy58000v3f/T/error.dump.4ece8f47d02acbe75bbacafb382d34b6.log

The log file has content:
ENV Summary:

  TIME: Wed Jun 12 2019 20:49:23 GMT+0530 (IST)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /usr/local/bin/ember
  - new
  - ember-quickstart
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/32/t6t2nn2x63s9k3dhh_3dmy58000v3f/T
  SHELL: /bin/bash
  PATH:
  - /Library/Frameworks/Python.framework/Versions/3.6/bin
  - /Users/<username>/hadoop/hadoop-2.8.1//bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /export/content/granular/bin
  - /Library/Frameworks/Python.framework/Versions/3.6/bin

  PLATFORM: darwin x64
  FREEMEM: 252014592
  TOTALMEM: 17179869184
  UPTIME: 576728
  LOADAVG: 2.3291015625,2.77587890625,2.935546875
  CPUS:
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.7.0
  - icu: 58.2
  - modules: 48
  - node: 6.11.3
  - openssl: 1.0.2l
  - uv: 1.11.0
  - v8: 5.1.281.107
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Unexpected token function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Unexpected token function
  - name: SyntaxError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: /private/var/folders/32/t6t2nn2x63s9k3dhh_3dmy58000v3f/T/ember-cli2019512-62366-1g20qh6.sb2uf03sor/node_modules/ember-source-channel-url/src/index.js:4
module.exports = async function(channelType) {
                       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/32/t6t2nn2x63s9k3dhh_3dmy58000v3f/T/ember-cli2019512-62366-1g20qh6.sb2uf03sor/node_modules/@ember/octane-app-blueprint/index.js:4:19)

**System information:**
ember-cli: 3.9.0
node: 6.11.3
os: darwin x64

I've tried clearing npm cache as well. Please help.

**Comment by NullVoxPopuli** [comment]
node 6 is not supported.
can you upgrade to node 8+?

**Comment by rwjblue** [comment]
:wave: Thanks for reporting! I think the main issue here is that Node 6 is unsupported (since its been EOL'ed by the Node folks). Should work properly if you update to Node 8 or higher.

Sorry for the troubles!

**Comment by manurampandit** [comment]
Thanks a lot @rwjblue  & @NullVoxPopuli 
It worked.
