### ISSUE TITLE
ember data blueprint removed?

### ISSUE THREAD

**Issue by frank06** [ember-cli/ember-octane-blueprint#125]
A few days ago I created a new app with this Octane blueprint and I could use `ember generate model`. Not anymore:

```bash
$ ember g model user
Unknown blueprint: model
```

I switched back to the previous app and the Ember Data blueprint does work with Octane. Versions of `ember-cli` and `ember-source` in `package.json` point to different commits (that is the only difference).

I tried to `npm install` those but still couldn't get the Ember Data blueprint to work. Not sure what changed.

**Comment by frank06** [comment]
It's an issue with Ember Data 3.11.

**Comment by joegaudet** [comment]
@frank06 I'm seeing the same thing, is there a workaround?

**Comment by NullVoxPopuli** [comment]
downgrade ember-data to 3.10

**Comment by MyTherese** [comment]
Hi im new to ember! How do you downgrade?

**Comment by contrerasmarc** [comment]
Same issue here :
ember-cli: 3.11.0
node: 12.5.0
os: win32 x64

**Comment by NullVoxPopuli** [comment]
just change ember-data in package.json to `~3.10.0`
