### ISSUE TITLE
`ember generate component foo-bar` (with no modifiers) generates a template-only component that throws an error on render

### ISSUE THREAD

**Issue by justinross** [ember-cli/ember-octane-blueprint#137]
Using ember-cli 3.11.0, in an app generated with the ember-octane-blueprint, `ember generate component foo-bar` creates appears to generate a template-only component by default:

![image](https://user-images.githubusercontent.com/1120106/62403138-2aac9a80-b540-11e9-93b3-6a69dbf189e8.png)

When trying to render this component (via angle-brackets or curlies), the browser throws this error: 
![image](https://user-images.githubusercontent.com/1120106/62403086-d6091f80-b53f-11e9-8afe-0edc971a9c88.png)

`ember generate component foo-bar --gc` (or `--cc`) creates a .js file as well, alongside the .hbs file:
![image](https://user-images.githubusercontent.com/1120106/62403148-3dbf6a80-b540-11e9-8567-5bdfb939cd8e.png)

but then ember-cli throws an error:
`(node:9959) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, symlink '/Users/username/posterkiosk-v3/app/components/foo-bar.js' -> '/var/folders/2z/wlt8fkc91ns4_nvrp7nynv_m0000gq/T/broccoli-9959zBmmLpkANVA0/out-176-broccoli_persistent_filter_template_compiler/posterkiosk-v3/components/foo-bar.js'`

/edit: I just realized, in case it matters, I created the new project via `npx ember-cli new appname -b @ember/octane-app-blueprint` earlier this afternoon, and don't have ember-cli installed globally, so I'm using `yarn ember generate component`.

**Comment by justinross** [comment]
`--cs --cc` appears to at least generate files that work. 

![image](https://user-images.githubusercontent.com/1120106/62481018-2661c680-b766-11e9-9a82-0205ee67db65.png)

**Comment by rwjblue** [comment]
FWIW - This is a result of the changes for the [emberjs/rfcs#481](https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md) which _just_ landed in ember-source master (which the Octane blueprint uses).

**Comment by justinross** [comment]
Yeah, I’m excited about the flat component structure. The blueprint just seems a little wonky with it at the moment.
