### ISSUE TITLE
TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible

### ISSUE THREAD

**Issue by csylaios** [ember-cli/ember-octane-blueprint#138]
Hi, i have migrated an ember app to octane, everything was working fine until 30 days ago, today i decided to upgrade to latest version of libs in package json and i am getting this error: `TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible`

does anyone know what this is?

with `"ember-cli": "github:ember-cli/ember-cli#619be9f8ce25ae1cada222421d11d196b41a3a4a",` and `"ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/7734bac947669e77afa84fc3546eea6255b223c3.tgz",` everything is working fine

**Comment by rwjblue** [comment]
@pzuraq - This seems related to recent changes we made on the args proxy, right?

**Comment by pzuraq** [comment]
I believe this should be fixed by the most recent release of `@glimmer/component`, users were reporting this on Discord yesterday as well, and they've reported it was fixed this morning.

**Comment by csylaios** [comment]
@rwjblue i changed glimmer component to `"@glimmer/component": "^0.14.0-alpha.10",` and it seems to be ok, thanks

**Comment by rwjblue** [comment]
Awesome, thanks y'all! Closing as resolved...
