### ISSUE TITLE
Update blueprint packages to latest

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-octane-blueprint#170]
Need to ensure that we sync the changes from https://github.com/ember-cli/ember-cli/pull/8816 into this blueprint. They _may_ already be done, but I'm not certain and I'd love help confirming (or updating).

**Comment by NullVoxPopuli** [comment]
in the last PR, we introduced `latest-version` which... looks up the latest version of a package -- should we do this for all packages so we don't need to sync so often?

**Comment by chancancode** [comment]
@NullVoxPopuli I don't think that is super related. These packages have semver ranges that we picked deliberately. It's really not different than any other upstream blueprint changes.

**Comment by rwjblue** [comment]
Octane was released in Ember 3.15! This repo has been deprecated (the blueprints that come with ember-cli are the source of truth again). I'm closing as this repo is being archived, but if you are still running into issues please file a new issue over on ember-cli's issue tracker.

Thanks for your help making Octane happen!!
