### ISSUE TITLE
Add example of new syntax

### ISSUE THREAD

**Issue by MelSumner** [ember-cli/ember-octane-blueprint#2]
- [x] write issue for sparkles
- [x] add example of new syntax when sparkles is updated in a way that will allow this to happen.

**Comment by NullVoxPopuli** [comment]
Sparkles issue: https://github.com/rwjblue/sparkles-component/issues/16

**Comment by NullVoxPopuli** [comment]
I temporarily got around this by just using a non-current version of `@ember-decorators/babel-transforms` --- which uses the old decorators proposal

**Comment by NullVoxPopuli** [comment]
This is implemented, not sure how far we want to go with examples though -- maybe that's where the guides come in eventually?
