### ISSUE TITLE
ember-cli: cannot read config file .ember-cli.js

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-octane-blueprint#211]
```
ember <whatever>

/home/gaurav/.config/yarn/global/node_modules/yam/lib/utils/io-utils.js:62
    throw "Cannot read config file: " + configPath;
    ^
Cannot read config file: /home/gaurav/dev/emberjs/something/.ember-cli.js
```

This likely is an issue with ember-cli@beta

Workaround: Step ember-cli back down to "~3.14.0"

**Comment by rwjblue** [comment]
Steps to reproduce?

**Comment by Gaurav0** [comment]
```
ember new something -b @ember/octane-app-blueprint
cd something
ember s
```

**Comment by rwjblue** [comment]
@Gaurav0 - What is the global `ember` version on your system?

**Comment by Gaurav0** [comment]
I'm using 3.14.0 globally. Dependencies were installed.

I have another idea:
I have a .ember-cli file in my home directory that looks like this:

```
{
  "yarn": true
}
```

Could that make a difference?

**Comment by iamx** [comment]
I had the same issue using 3.14.0-beta.2 

For me the workaround was running `yarn install` within the **something** folder.

Have you tried installing all the dependencies again?

**Comment by rwjblue** [comment]
FWIW, this was fixed in https://github.com/ember-cli/ember-cli/pull/8899
