### ISSUE TITLE
How to use Glimmer component API

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-octane-blueprint#41]
#38 has removed `sparkless-component` based on the conversation at https://github.com/ember-cli/ember-octane-blueprint/issues/37#issuecomment-464350307

Now than the `sparkless-component/tracked` is not available anymore, I wonder how Glimmer/Ember Component API works

cc @rwjblue / @NullVoxPopuli

**Comment by rwjblue** [comment]
You would use the normal @glimmer/component API directly. The API isn’t terribly different than sparkles-component (other than tracked coming from a different place).

**Comment by ppcano** [comment]
@rwjblue 

1)
Atm, it is not obvious (at least from a new Glimmer user) which is the  API.  I have tried

```
import Component from '@ember/component';
import { tracked } from '@ember/object';

//import Component, { tracked } from '@ember/component';
//import { tracked } from '@glimmer/tracking';

export default class HolaComponent extends Component {
  @tracked current = 0;
}
```

2) Once, we get this working, we may consider adding a Note in the Readme to the `sparkless-component` and `ember-decorators` to encourage the usage of this addon instead?

**Comment by rwjblue** [comment]
@ppcano - I just ran through the work flow and there are a number of things to fix (I'm adding issues here for tracking them separately), but the basic gist is:

```js
import Ember from 'ember';
import Component from '@glimmer/component';

// needed until we add a public module for this in ember-rfc176-data
const tracked = Ember._tracked;

export default class TesterooComponent extends Component {
  @tracked count = 0;

  increment() {
    this.count++;
  }
}
```

Check out the individual commits [here](https://github.com/rwjblue/octane-app-20190219/commits/master) for a basic rundown of the changes needed.

**Comment by rwjblue** [comment]
Actually, y'all have already fixed all the specific issues I ran into (thanks for being on top of things!), they just needed to be released so I tagged 0.5.0...

**Comment by NullVoxPopuli** [comment]
the package.json's don't auto-update atm, so we need some C.I. help if we're going to release via github releases (which'd be slick).  I'll update things at release 0.5 to npm.

**Comment by NullVoxPopuli** [comment]
just learned force-pushing a tag clears the description / title on github releases. boo.
anyway, the 0.5.0 packages should eventually end up on npm now

**Comment by rwjblue** [comment]
whoops, sorry @NullVoxPopuli (thanks for fixing)

**Comment by NullVoxPopuli** [comment]
finally released ;)

**Comment by ppcano** [comment]
@rwjblue 

 I don't know if you find many blockers to start promoting more the octane blueprints, but I think `Ember._tracked` is one. 

```
// needed until we add a public module for this in ember-rfc176-data
const tracked = Ember._tracked;
```

Is there the possibility to prioritize it? I think it is under the `EMBER_METAL_TRACKED_PROPERTIES` feature flag, so it may not be a big issue if it may change later?

**Comment by gossi** [comment]
Can you explain `@glimmer/tracking` vs `@ember/-internals/metal/tracked` ? Which one will become the public one?

**Comment by rwjblue** [comment]
The merged RFC explicitly states that `@glimmer/tracking` is the public module for accessing the `@tracked` decorator.

**Comment by ppcano** [comment]
I gave a try to `import { tracked } from '@glimmer/tracking'` but it does not work atm. I will be using `Ember._tracked` until the API becomes public.

**Comment by gossi** [comment]
Thanks @rwjblue that makes sense to use `@glimmer/tracking` - I've asked this mainly because it seems two similar APIs that have different implementations and don't even know each other. I guess the question is more, why maintain two things that _look_ like the same thing?

**Comment by rwjblue** [comment]
@gossi - I really do not grok what you mean here. The module that will be resolved by `@glimmer/tracking` within an Ember app _**is**_ the code you are referencing.

More details to _hopefully_ get us on the same page:

* [this is the decorator](https://github.com/emberjs/ember.js/blob/58a38e8ce56cac1d290bcf8115cdd66ea9efaac6/packages/%40ember/-internals/metal/lib/tracked.ts#L103)
* [this is where it is exported from the @ember/-internals/metal](https://github.com/emberjs/ember.js/blob/58a38e8ce56cac1d290bcf8115cdd66ea9efaac6/packages/%40ember/-internals/metal/index.ts#L52)
* [this is where its set on the Ember global](https://github.com/emberjs/ember.js/blob/58a38e8ce56cac1d290bcf8115cdd66ea9efaac6/packages/ember/index.js#L276)
- [ ] [this project needs to be updated to map @glimmer/tracking to Ember._tracked](https://github.com/ember-cli/ember-rfc176-data)
* [this is where we map from globals to modules](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill)

**Comment by rwjblue** [comment]
@ppcano - Yep, it absolutely is important. Here are the steps needed to make `import { tracked } from '@glimmer/tracking'` work:

- [ ] Add an entry to ember-rfc176-data and release
- [ ] Bump ember-rfc176-data in babel-plugin-ember-modules-api-polyfill and release
- [ ] Bump babel-plugin-ember-modules-api-polyfill in ember-cli-babel and release
- [ ] Update this blueprint to use the newly released ember-cli-babel as a minimum version

**Comment by ppcano** [comment]
I will work on 👆

**Comment by gossi** [comment]
@rwjblue My fault, I was seeing the code you posted the links to, but I was also seeing this one here: [`@glimmer/tracking`](https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/tracking/src/tracked.ts)

I was wondering, how the code I linked is related to the code you linked to? Because when you say `@glimmer/tracking` I would expect the code at the location I linked here. Is there some unintentional confusion happening?

**Comment by ppcano** [comment]
@gossi Look at https://github.com/ember-cli/ember-rfc176-data/pull/113.

Ember will re-export `Ember._tracked` (wrapper for `@glimmer/tracking`) as `@glimmer/tracking` module.

**Comment by ppcano** [comment]
Closing in favor of https://github.com/ember-cli/ember-octane-blueprint/pull/48 and https://github.com/ember-cli/ember-rfc176-data/pull/113
