### ISSUE TITLE
Maybe a bug with nested routes

### ISSUE THREAD

**Issue by flashios09** [ember-cli/ember-octane-blueprint#51]
Hi,
i created an app(a month ago) using this repo to test ember octane, i generated those routes via ember cli:
* admin
* admin/dashboard
* admin/establishments
* admin/customers

here admin is just a **prefix**(an engine), the user must connect to have access to `/admin/any-thing` 

the problem that the child route `admin/any-child-route` isn't being rendered in the browser, this is a screenshot, ember inspector detect that i'm inside `admin/establishments`:
![image](https://user-images.githubusercontent.com/1313482/53344207-6b114800-3912-11e9-849e-200d779e75ec.png)

the generated files:
```js
// emberjs/src/ui/routes/admin/route.ts
import Route from '@ember/routing/route';

export default class AdminRoute extends Route {
}
```
```hbs
{{!-- emberjs/src/ui/routes/admin/template.hbs --}}
this is admin route
<hr>
{{outlet}}
```
```js
// emberjs/src/ui/routes/admin/establishments/route.ts
import Route from '@ember/routing/route';

export default class AdminEstablishmentsRoute extends Route {
}
```
```hbs
{{!-- emberjs/src/ui/routes/admin/establishments/template.hbs --}}
<h1>admin/Establishments</h1>
{{outlet}}
```
the router:
```js
import EmberRouter from "@ember/routing/router";
import config from "../config/environment";

const Router = EmberRouter.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('admin', function() {
    this.route('Establishments', {path: '/Establishments'});
    this.route('Roomtypes', {path: '/Roomtypes'});
  });
});

export default Router;
```
have i missed something ?

another question, how to update this app, what to update ? ember-source ?

![image](https://user-images.githubusercontent.com/1313482/53344781-d0b20400-3913-11e9-8655-924db0246ada.png)

**Comment by NullVoxPopuli** [comment]
I don't know anything about engines, but for upgrading, you can usually just change the sha to the latest ember commit.
or, have a look here: https://www.emberjs.com/builds/canary/

**Comment by flashios09** [comment]
@NullVoxPopuli thanks, i will update it now and see if the problem persist !
> I don't know anything about engines
i don't use `ember-engine`, i mean something like an **engine**
those are a normal/classic generated routes via ember cli

![image](https://user-images.githubusercontent.com/1313482/53345133-841af880-3914-11e9-9c99-5f4d750741b7.png)

please take a look at the code and tell me if i have missed something ?

**Comment by NullVoxPopuli** [comment]
is this repo published somewhere we can look at? something non-obvious-to-me is happening

**Comment by flashios09** [comment]
i found it, just a **case** error !
we can't have **capital letter** in route name

![image](https://user-images.githubusercontent.com/1313482/53345735-dc9ec580-3915-11e9-8869-7697e19d7628.png)

just replacing `Establishments` by `establishments` in the route name :)
```js
import EmberRouter from "@ember/routing/router";
import config from "../config/environment";

const Router = EmberRouter.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('admin', function() {
    this.route('establishments', {path: '/Establishments'});
    this.route('roomtypes', {path: '/Roomtypes'});
  });
});

export default Router;
```

![image](https://user-images.githubusercontent.com/1313482/53345874-2d162300-3916-11e9-9f85-2281a8561c28.png)

**Comment by NullVoxPopuli** [comment]
neato
