### ISSUE TITLE
blueprints do not work with node 10

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-octane-blueprint#64]
repro
```bash
notion install node 10
npx ember-cli new my-app -b ember-octane-app-blueprint
```
```bash
npx: installed 778 in 17.26s
Error creating new application. Removing generated directory `./my-app`
Cannot find module '/tmp/ember-cli11926-2678-jbwkfj.9u4x/node_modules/ember-octane-addon-blueprint/package.json'


Stack Trace and Error Report: /tmp/error.dump.4731720e03081a022963180814ce7fac.log
```

**Comment by NullVoxPopuli** [comment]
or... at all. just tried node 8. 
I don't understand. this worked on my home computer last night :-\

**Comment by NullVoxPopuli** [comment]
related: https://www.reddit.com/r/emberjs/comments/axjvw7/a_preview_of_emberjs_octane/ehvsrke/

**Comment by NullVoxPopuli** [comment]
that error in ember-cli is the one from reddit and the one someone else confirmed in discord, so that's good! :)

**Comment by rwjblue** [comment]
@NullVoxPopuli 	would you mind commenting on the reddit thread? the issue is fixed (I just confirmed via generating via the blueprint from scratch).
