### ISSUE TITLE
Linked Ember data using jQuery

### ISSUE THREAD

**Issue by Charizard** [ember-cli/ember-octane-blueprint#66]
Created an app using this blueprint and when trying to do a `this.store.findAll('post');` it quickly hits a `Cannot read property 'ajax' of undefined` and noticed that the linked ember-data [here](https://github.com/ember-cli/ember-octane-blueprint/blob/master/packages/%40ember/octane-app-blueprint/files/package.json#L38) is still using jQuery.

**Comment by Charizard** [comment]
I realise ember-data is still in progress in making jQuery optional https://github.com/emberjs/data/issues/5320. So, jQuery isn't optional after all? 🤷‍♂️

**Comment by ppcano** [comment]
This is a known issue on the [Octane Tracking issue](https://github.com/emberjs/ember.js/issues/17234)

I think https://github.com/emberjs/data/pull/5386 will solve it.

**Comment by Charizard** [comment]
@ppcano Makes sense. Thanks!!

**Comment by NullVoxPopuli** [comment]
Well, this is still an issue. I'm hoping this lights some fire under the butts of ember-data. :)
(Though, after emberconf, I'll have time to help out those efforts)

**Comment by Charizard** [comment]
@NullVoxPopuli Then, do you want this to be re-opened so the fire burns brightly 😛 ?

**Comment by NullVoxPopuli** [comment]
yes :)
Also, I rebased: https://github.com/emberjs/data/pull/5900

**Comment by rwjblue** [comment]
While we wait for progress there, we should add `ember-fetch` and setup its ember-data integration to avoid issues without jQuery.

**Comment by NullVoxPopuli** [comment]
probably. _anything_ to reduce friction is good, imo

**Comment by Charizard** [comment]
@rwjblue @NullVoxPopuli Yes. I did not know about `ember-fetch`'s `ember-data` integration until I brought this up in Twitter.

**Comment by rwjblue** [comment]
FWIW, ember-data's master branch _just_ merged a PR that should allow usage without jQuery and without special customization of the application adapter (which is what the ember-fetch mixin does).

See https://github.com/emberjs/data/pull/5900

**Comment by NullVoxPopuli** [comment]
closed by: https://github.com/ember-cli/ember-octane-blueprint/pull/77
