### ISSUE TITLE
will there be a separate octane addon blueprint repo?

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-octane-blueprint#7]
This conversation was started at https://github.com/ember-cli/ember-cli/pull/8157#issuecomment-449792234

I suggested @NullVoxPopuli this project could have an addon structure like:

```

ember-octane-blueprint
   blueprints
      octane-app
      octane-addon

```

And users could execute the commands:

```
ember new my-app -b octane-app
ember addon my-addon -b octane-addon
```

I have tested how `ember-cli` could be extended to load the octane-blueprints from another project.  https://github.com/ppcano/ember-cli/commit/01eef87bc954ca33c5928a2471d1c28b8a8f1663 looks to be working (the code should be improved).

Would the above configuration make sense?

I think the main incovenient with having an independent project for the octane-addon (either this project or a new one) is that the current [module-unification-addon blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/module-unification-addon/index.js) extends the [addon blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/index.js), so we will end up duplicating a lot of code.

cc @rwjblue

**Comment by NullVoxPopuli** [comment]
Closing due to discussions in  https://github.com/ember-cli/ember-cli/pull/8384 :)

Monorepo all the way :)
