### ISSUE TITLE
Deprecate npm`ember-octane-blueprint` package 

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-octane-blueprint#72]
https://www.npmjs.com/package/ember-octane-blueprint

Search engines  have indexed this package and it appears on the octane blueprint searchs, but the package  is deprecated and the documentation is not up-to-date.

cc @NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
Thanks, I'll publish a deprecation package soon!(ish)

**Comment by NullVoxPopuli** [comment]
done!
