### ISSUE TITLE
Upgrade ember-data package on octane app blueprint

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-octane-blueprint#73]
The Ember Data `master` branch has added improvements for Octane apps:

- `jquery` removal
-  new ED blueprints to use Native syntax

The question is which would be the strategy to set the `ember-data` version on the app blueprint:

1) We could ask the ED team to make a beta release and use it.
2) We could follow the same procedure with `ember-data` as with the `ember-cli/ember.js` packages and pick dynamically the latest commit version from `ember-data/master`.

cc @rwjblue

**Comment by rwjblue** [comment]
@ppcano - Hmm, good question. I don't really have any objection to either of those two options. I'd say lets go with #2 for now since we already _basically_ have the infrastructure to do it.

/cc @runspired @igorT @hjdivad @dgeb
