### ISSUE TITLE
Remove MU from octane addon blueprint

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-octane-blueprint#74]
https://github.com/ember-cli/ember-octane-blueprint/pull/68 removed MU from the app blueprint.

Similar 👆changes must be done for the addon blueprint, I haven't reviewed all the required changes but at least the `dummy` app needs to be updated. 

@zinyando You worked on the previous one (thank you!), do you want to take a stab on this issue as well?

**Comment by zinyando** [comment]
@ppcano yeah sure I can create a PR for that. I don't know how I forgot to update the dummy app. Let me know if there is anything else that needs to be fixed

**Comment by ppcano** [comment]
@zinyando Great!

I have quickly tested the latest changes and I did not catch other issues. I created https://github.com/ember-cli/ember-octane-blueprint/pull/71 to fix one issue after the MU removal.

In case it helps, I usually follow the recommendation described on the [Building/Contributing section](https://github.com/ember-cli/ember-octane-blueprint#buildingcontributing) to use my local blueprints and test them creating apps or addons.

**Comment by zinyando** [comment]
@ppcano can you take a look at https://github.com/ember-cli/ember-octane-blueprint/pull/75? I followed the layout in https://github.com/ember-cli/ember-addon-output

**Comment by NullVoxPopuli** [comment]
I just generated an addon:
```
$ npx ember-cli addon my-addon2 -b @ember/octane-addon-blueprint
npx: installed 779 in 39.254s
installing octane-addon-blueprint
  create .editorconfig
  create .ember-cli.js
  create .eslintrc.js
  create .travis.yml
  create CONTRIBUTING.md
  create LICENSE.md
  create README.md
  create addon/index.js
  create config/ember-try.js
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create index.js
  create package.json
  create tests/dummy/app/app.js
  create tests/dummy/app/index.html
  create tests/dummy/app/resolver.js
  create tests/dummy/app/router.js
  create tests/dummy/app/routes/application/template.hbs
  create tests/dummy/app/styles/app.css
  create tests/dummy/app/templates/application.hbs
  create tests/dummy/config/environment.js
  create tests/dummy/config/optional-features.json
  create tests/dummy/config/targets.js
  create tests/dummy/public/robots.txt
  create tests/index.html
  create tests/test-helper.js
npm: Installed dependencies
Successfully initialized git.
```

looks like we're good to go! :+1:
