### ISSUE TITLE
Using this.store.findAll() throws an exception on a newly-created app

### ISSUE THREAD

**Issue by Kerrick** [ember-cli/ember-octane-blueprint#87]
:wave: I'm super excited to test out octane, so I used the QuickStart from the guides linked in the talk at EmberConf today. I did `ember new magic-university -b @ember/octane-app-blueprint` and generated a model + application route, but got an exception straight away. Am I just peeking my head in the door too early? (Code here: https://github.com/Kerrick/octane-preview-test/commit/4b04e1a6aabbe3bdad46469f7edc7d88c0e13e7d)

```
Error while processing route: index Cannot read property 'catch' of undefined
```

<img width="915" alt="Screen Shot 2019-03-20 at 7 09 06 PM" src="https://user-images.githubusercontent.com/552093/54731439-74758500-4b4b-11e9-871d-8ebf7e1d68d4.png">

**Comment by Kerrick** [comment]
Seemingly related: https://github.com/emberjs/data/issues/5918

**Comment by rwjblue** [comment]
Thank you for reporting!

**Comment by acorncom** [comment]
This can be closed, fixed by https://github.com/emberjs/data/pull/5925
