### ISSUE TITLE
failed when used this blueprint on windows 

### ISSUE THREAD

**Issue by smile921** [ember-cli/ember-octane-blueprint#88]
![image](https://user-images.githubusercontent.com/1404755/54805148-021eb500-4cb1-11e9-8ea3-604fa2cb82a5.png)
try to use this bluprint on windows  failed

the dum log below 

=================================================================================

ENV Summary:

  TIME: Fri Mar 22 2019 14:42:53 GMT+0800 (GMT+08:00)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\Frere921\AppData\Local\Yarn\Data\global\node_modules\ember-cli\bin\ember
  - new
  - octane-app
  - -b
  - @ember/octane-app-blueprint
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\Frere921\AppData\Local\Temp
  SHELL: null
  PATH:
  ......
  PLATFORM: win32 x64
  FREEMEM: 8484016128
  TOTALMEM: 17065340928
  UPTIME: 713008
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz - 2295
  - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz - 2295
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: MODULE_NOT_FOUND
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'C:\Users\Frere921\AppData\Local\Temp\ember-cli2019222-21928-bgj8ea.j0fe\node_modules\@ember\octane-app-blueprint\package.json'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'C:\Users\Frere921\AppData\Local\Temp\ember-cli2019222-21928-bgj8ea.j0fe\node_modules\@ember\octane-app-blueprint\package.json'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'C:\Users\Frere921\AppData\Local\Temp\ember-cli2019222-21928-bgj8ea.j0fe\node_modules\@ember\octane-app-blueprint\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at InstallBlueprintTask._validateNpmModule (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:133:15)
    at _createTempFolder.then.then.modulePath (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:92:14)
    at tryCatcher (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at publish (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:481:7)
    at flush (D:\nodejs\Yarn\Data\global\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)

=================================================================================

**Comment by NullVoxPopuli** [comment]
what happens when you try `npx ember-cli new octane-app -b @ember/octane-app-blueprint`?

**Comment by smile921** [comment]
just failed then some tmp folder files were removed ,
then leave a dump file log as you see above .
I don't know what to do to find out more

**Comment by NullVoxPopuli** [comment]
excellent! glad it's repeatable!
I'll try to find someone with a windows machine to take a look. thanks for reporting! <3

**Comment by makepanic** [comment]
I've tried `npx ember-cli new octane-app -b @ember/octane-app-blueprint` in a fresh http://modern.ie windows 10 vm.
Weirdly enough it created the project without issues.

![20190322-090330](https://user-images.githubusercontent.com/1205444/54810439-6d06c680-4c86-11e9-8f5a-bc2fae8c0436.png)

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/54813422-8ca9e900-4c9e-11e9-93b0-2d84bcff7b01.png)

**Comment by gulench** [comment]
I also ran into this issue. However, using a local blueprint, as mentioned in [README.md -> Building/Contributing](https://github.com/ember-cli/ember-octane-blueprint#buildingcontributing), works.

**Comment by NullVoxPopuli** [comment]
Is it maybe cache related? Does yarn/npm cache clean help?

**Comment by gulench** [comment]
I think I've got the issue. There was a `%USERPROFILE%\node_modules` directory and somehow this directory was getting used when `ember-cli` was run. When I **got rid of that directory**, `ember new ... -b @ember/octane-blueprint-app` ran successfully.

I'm not sure how the `node_modules` directory got created in my `%USERPROFILE%` directory. I could've earlier run `npm install` unintentionally while I was in the `%USERPROFILE%` directory.

It looks like the presence of `%USERPROFILE%\node_modules` directory was interfering with the node module resolution process, and `ember-cli` **failed to resolve** the *blueprint* module. This stackoverflow thread may provide some background to this: [Why does npm install local packages in my home directory?](https://stackoverflow.com/questions/50894761/why-does-npm-install-local-packages-in-my-home-directory).

The point to note here is that `ember new ...` worked whereas `ember new ... -b some-blueprint` did not work. Maybe we could make `ember-cli` resolve blueprints similar to how it resolves other modules.

**Comment by NullVoxPopuli** [comment]
@gulench do you use a node version manager of any kind?

**Comment by smile921** [comment]
I found one case that the project folders and the template files created but later the npm install failed when one or some dependents failed by a network slowly , then the cli clean all the things created

**Comment by gulench** [comment]
@NullVoxPopuli I’m not using a node version manager. I’m running the current LTS release of `node`, and the current version of `yarn`.

After I got rid of the `node_modules` from my home directory, things are running fine.

**Comment by MelSumner** [comment]
I wasn't able to create an addon or app on my Windows machine when I used these instructions in the README:
![image](https://user-images.githubusercontent.com/4587451/55742285-ed525900-59f4-11e9-9319-7beda558a9a3.png)

But when I read through the entire README and followed the instructions under "Building and Contributing", I was able to successfully create both an addon and an app on Windows: 
![image](https://user-images.githubusercontent.com/4587451/55742248-d4e23e80-59f4-11e9-995f-f6567c260497.png)

**Comment by ASH-Anthony** [comment]
Thanks @MelSumner. Your suggestion works by installing the blueprint locally

**Comment by lifeart** [comment]
$ npx ember-cli new glimmer -b @glimmer/blueprtint
npx: installed 783 in 30.38s

Error creating new application. Removing generated directory `./glimmer`
Command failed: npm install @glimmer/blueprtint
npm ERR! code E404
npm ERR! 404 Not Found: @glimmer/blueprtint@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lifeart\AppData\Roaming\npm-cache\_logs\2019-04-27T07_38_31_410Z-debug.log




Stack Trace and Error Report: C:\Users\lifeart\AppData\Local\Temp/error.dump.8ff47cf0e6307ffcac0f0b7791671220.log

**Comment by NullVoxPopuli** [comment]
@lifeart spelling error? Maybe?

**Comment by lifeart** [comment]
@NullVoxPopuli nope, looks lke version has no slash in windows.
ember-cli trying to load `@glimmer/bluprint + @latest`  as `@glimmer/blueprtint@latest`

**Comment by NullVoxPopuli** [comment]
maybe try quotes around it? or git-bash? what shell are you using?

**Comment by lifeart** [comment]
@NullVoxPopuli `git bash for windows`
![image](https://user-images.githubusercontent.com/1360552/56849866-ec7d5a80-6902-11e9-9d53-441d585955ca.png)

**Comment by lifeart** [comment]
same for `cmd` and `power shell` 
![image](https://user-images.githubusercontent.com/1360552/56849883-3fefa880-6903-11e9-8a5c-97b18e8b66cd.png)

**Comment by lifeart** [comment]
Octane blueprint looks alive:

![image](https://user-images.githubusercontent.com/1360552/56850006-e38d8880-6904-11e9-9a8c-d5d6eddd29f3.png)

Trying to figure out that happening with glimmer blueprint, @MelSumner approach
`ember new my-octane-app -b ..\repos\glimmer.js\packages\@glimmer\blueprint` working, but it's tricky way

**Comment by NullVoxPopuli** [comment]
what if you copy paste: `npx ember-cli new my-app -b @glimmer/blueprint` (I think I see typos in your screenshot :) )

**Comment by lifeart** [comment]
@NullVoxPopuli, thanks alot! I'm stupid and has typo in blueprint name 🦆

**Comment by NullVoxPopuli** [comment]
@lifeart <3 naw, I do stupid stuff all the time, too. Shells need spellcheck. but like.. for all the weird programmy things we type, not just normal words on whatever language

**Comment by NullVoxPopuli** [comment]
Looks like this is working -- if anyone is having any issues with Octane and Windows, please feel free to open a new issue <3
