### ISSUE TITLE
Blueprint fails with ember-data version error

### ISSUE THREAD

**Issue by scalvert** [ember-cli/ember-octane-blueprint#93]
Following the [Quickstart](https://octane-guides-preview.emberjs.com/release/getting-started/quick-start/), generating a new Octane app from the blueprint fails during the dependency installation step. The error indicates an invalid `ember-data` version.

Steps to reproduce:

1. `npm install -g ember-cli`
2. `ember new ember-quickstart -b @ember/octane-app-blueprint` or `ember new ember-quickstart -b @ember/octane-app-blueprint --yarn`

Results in the following error:

```
Error creating new application. Removing generated directory `./ember-quickstart`
Command failed: yarn install --non-interactive
error Can't add "ember-data": invalid package version undefined.

yarn install v1.15.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.



Stack Trace and Error Report: /var/folders/3q/5x6gzths7b97lq08vx_cb0g4000gyd/T/error.dump.3d443c26e1cb6944c55d4bc317b013cd.log
```

The version of `ember-data` that's in the package.json is `"ember-data": "github:emberjs/data#1495b780952a1b1cb53060114490ba9554c1341d"`

Looking at [that commit in `emberjs/data`](https://github.com/emberjs/data/commit/1495b780952a1b1cb53060114490ba9554c1341d), it looks like CI is failing when doing compatibility testing with ember addons.

**Comment by scalvert** [comment]
Question: does it make sense to tie this blueprint to the latest commit rather than latest release (I realize there may be compatibility requirements for Octane apps)?

**Comment by scalvert** [comment]
Confirmed that updating the `ember-data` version in package.json to `1df833396855d956b817540923dd89338463fec2` (last green CI commit) resolves the issue.

**Comment by ijlee2** [comment]
> Confirmed that updating the `ember-data` version in package.json to `1df833396855d956b817540923dd89338463fec2` (last green CI commit) resolves the issue.

Thank you for this solution, @scalvert . I was just trying out Octane and ran into the same issue.

**Comment by NullVoxPopuli** [comment]
anybody want to PR a fix to both app and addon blueprints that pins the last green ember-data commit? :)

**Comment by rwjblue** [comment]
> Question: does it make sense to tie this blueprint to the latest commit rather than latest release (I realize there may be compatibility requirements for Octane apps)?

At the time, no release included the changes we required (specifically we needed ember-data to work without jQuery).

**Comment by scalvert** [comment]
I figured as much. I can open PRs to fix.

**Comment by rwjblue** [comment]
Thanks @scalvert
