### ISSUE TITLE
Unpin ember-data version

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-octane-blueprint#95]
Once https://github.com/emberjs/data/pull/5900 lands in a released version of ember-data (likely 3.10.0-beta.1) we should update to use the released / tagged version of ember-data.

**Comment by NullVoxPopuli** [comment]
ember data pinned here: https://github.com/ember-cli/ember-octane-blueprint/blob/master/packages/%40ember/octane-app-blueprint/files/package.json#L37
